metrics-server:
  image:
    repository: registry.k8s.io/metrics-server/metrics-server
    # Overrides the image tag whose default is v{{ .Chart.AppVersion }}
    tag: ""
    pullPolicy: IfNotPresent
  fullnameOverride: "metrics-server"

  service:
    type: ClusterIP
    port: 443
    annotations: {}
    labels: {}
  
