metallb:
  enabled: true
  fullnameOverride: metallb
  controller:
    logLevel: info
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 100Mi
  speaker:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 100Mi

  addresses:
    ip-test-pool:
      addresses:
      - 192.168.1.70-192.168.1.80
