cilium:
  cluster:
    name: kubernetes
  operator:
    replicas: 1
  k8sServiceHost: 192.168.1.159
  k8sServicePort: 6443
  ipam:
    mode: cluster-pool
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1500m
      memory: 1250Mi
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: lets-encrypt-production
          kubernetes.io/ingress.class: traefik
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - &host hubble.xalab.io
        tls:
          - hosts:
              - *host
            secretName: tls-secret
