cilium:
  cluster:
    name: kubernetes
  operator:
    replicas: 1
  k8sServiceHost: 192.168.1.60
  k8sServicePort: 6443
  ipam:
    mode: cluster-pool
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1500m
      memory: 1250Mi
