cilium:
  enabled: true
  initialInstall: true
  #upgradeCompatibility: "1.13"
  operator:
    rollOutPods: true
  bpf:
    autoMount:
      enabled: true
  extraEnv:
    - name: TZ
      value: "America/New_York"
  endpointRoutes:
    enabled: true
  hubble:
    relay:
      enabled: true
    ui:
      enabled: true
