external-secrets:
  enabled: true
  installCRDs: true
  crds:
    annotations:
      argocd.argoproj.io/sync-options: ServerSideApply=true

      

  resources:
    limits:
      cpu: 50m
      memory: 80Mi
    requests:
      cpu: 10m
      memory: 40Mi
  dnsPolicy: None
  dnsConfig:
    nameservers:
      - 192.168.1.165
  deploymentAnnotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true

