cert-manager:
  installCRDs: true
  dns01RecursiveNameservers: "10.104.55.56:53"
  dns01RecursiveNameserversOnly: true
  podDnsPolicy: "None"
  podDnsConfig:
    nameservers:
      - "10.104.55.56"

  enableCertificateOwnerRef: true
  prometheus:
    enabled: false
  resources:
    limits:
      cpu: 250m
      memory: 96Mi
    requests:
      cpu: 10m
      memory: 48Mi
  webhook:
    resources:
      limits:
        cpu: 100m
        memory: 48Mi
      requests:
        cpu: 10m
        memory: 24Mi
  cainjector:
    resources:
      limits:
        cpu: 50m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 90Mi
