---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-password 
  namespace: external-dns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  target:
    name: pihole-password 
    creationPolicy: Owner
  data:
    - secretKey: EXTERNAL_DNS_PIHOLE_PASSWORD
      remoteRef:
        key: /external-dns/EXTERNAL_DNS_PIHOLE_PASSWORD