apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: vm-scrape-config
spec:
  relabelConfigs:
  - action: replace
    sourceLabels:
    - __meta_kubernetes_node_name  # Use this if running in Kubernetes
    targetLabel: instance  # This will replace IPs with node names