apiVersion: operator.victoriametrics.com/v1beta1
kind: VMScrapeConfig
metadata:
  name: vm-scrape-config
spec:
  relabelConfigs:
  - action: replace
    sourceLabels: [instance]
    regex: "192.168.1.60:900"
    replacement: "cp"
    targetLabel: instance
  - action: replace
    sourceLabels: [instance]
    regex: "192.168.1.61:900"
    replacement: "node1"
    targetLabel: instance