---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: vm-grafana-secret
spec:
  encryptedData:
    admin-password: AgCtd7tziBpvagKGqQgdKfKj6wbEUg3G06+lmArdKABdWBtmS4iLE/Fz39N5Tp3bafM4OE8YO8qdCoH+4zSEwbMeA8JfBlHC+LcAE+kaTNWsxm97Hrl2LJA3LXV4AybZKInd5OpJ+d8/LTQvzQv1a794mThIkVrCLJi+BMdHnH7V9goDkLEIYHMn0qaum4w1VGdqdBJouSsoSTX7dJQEjPVtpybKACBo+M1rnEAJcCCn8tnht8jWbiuDOgDObgL3fXuECzIFCoeGKwEOqzDSM+m1FlQA4TnFV9k2yuWLrf4UtuQZAAvUwDfrH+UipxzHFyh16ixBHOqGVlrhHgwmEp0CJoCPjkpwpKwuMnEx9/WyLgaNHGr1DhexqdKlomfHsx1MRNb1AHM/ww4RMh+Hs6RdDUew8WQ8D2j/LrYNKczmgEp+/GODaOv28jKH6H1lcTZqNGW/mAQKnaTay9gxtoCy09ZYoEpxdxi3H+0ZAvt9UlfI0yvaxBjWFZvEsIF+lLjaZC5zrEF8gho0Z20olSE4pF/JUUJuh39eQ4kLrKT4BBiYjginkcrrxB9pRJAtNKRvZiwtGp/ZTejg/wjaa5ZU9/fXoJ90LZ9j4QQOrTRCkyTalceL4RiOgOWuezQSWQeCUSfsUDxuKzaHA5pdXNAamVJD9uLTlKH+ipJ95hFu89/VbWAoXvIMCtRYaYaP/G1zF4txiVnK/8iwvXb19Hvr
    admin-user: AgC1JaLLwjBSfeVWn/X1tN4iBbvI7rey9uh8hr0NSsN8WtMG7AfL/em7bbCiof6NxvNfd8+gWphL6WlyKmq2Ubbb08BkFZPQa6ZCw1zAza+3u8v4cY9o58BY4SZGvkTc2yM3hymHj1u53sOVj5VXQ9jsUUOHtRqbCP+fwJ3UNrdkFhqWxnWoMB/OMuDXjblG0JXK3lGatsHtoTh/b9aBc+w3KtyANom3l4P0TlLLFDh+tY+r1U+nA9WH72qO4hwqTZMFFt0BODH7yiA4xI43aCc5CdzkJCvRmJue+xiHJUsZWmyIVfU26HEHncwEzUhqjrOzcCgadIikzhXZo4I7WGM60AkLQ0/VyN72NJ59ivBx9E+Ybbt0S2T7m+cZ3DSC0yIrYgo916Flra8/vtT97Z2FX7BWQod8q0mcdNjnxcYl8ShTdx90XOl8St0J1cZjnQYp9LCcD9HEO572P14X+RgeV7V0Vl2tDYPQkxaiNLj8hQBh/r5L0ULHwSe80jhMMBzgQeOIQ/KTQ1TGEP0SZZWwe+OPwpTSNNzJa56GkKaSCQEfdNustrT/NkJli1iZEGaWu6vNjwCi2jJzLNkNTVvzk9h6WenzBHxjLUSehRRwlyAn4cGVF33yzxWZOMJIlpn+JhisnHzqHDtis8+vsrSzmGIblqlSPPxxppPDAn/7f+fEK0rugBRBVuTqdGHfeEM6t9u3oJZreA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: vm-grafana-secret
    type: Opaque
