---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vm-grafana-secret
  namespace: victoria-metrics-k8s-stack
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  target:
    name: vm-grafana-secret
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: /grafana/admin-user
    - secretKey: admin-password
      remoteRef:
        key: /grafana/admin-password