{{- if .Values.alloy.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: {{ .Release.Namespace }}
data:
  {{ .Values.alloy.configMap.key }}: |
{{ tpl .Values.alloy.configMap.content . | indent 4 }}
{{- end }}