{{- with .Values.alloy.configMap }}
  {{- if .create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-config
  namespace: {{ $.Release.Namespace }}
data:
  {{ .key }}: |
{{ tpl .content $ | indent 4 }}
  {{- end }}
{{- end }}