# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.7.0/charts/library/common/values.schema.json
controllers:
  main:
    strategy: Recreate
    replicas: 1

    containers:
      app:
        image:
          repository: ghcr.io/gethomepage/homepage
          tag: v0.10.9
          pullPolicy: IfNotPresent

        env:
          TZ: America/NewYork

        # envFrom:
        #   - secretRef:
        #       name: homepage-env

        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &port 3000
              initialDelaySeconds: 60
              periodSeconds: 10
              timeoutSeconds: 1
              failureThreshold: 3
          readiness: *probes

serviceAccount:
  create: true

service:
  app:
    controller: main
    type: LoadBalancer
    ports:
      http:
        port: *port

ingress:
  main:
    enabled: true
    labels:
      # This label will enable discover of this deployment in Homepage
      # gethomepage.dev/enabled: 'true'
    annotations:
      # These annotations will configure how this deployment is shown in Homepage
      gethomepage.dev/name: 'Homepage'
      gethomepage.dev/description: 'A modern, secure, highly customizable application dashboard.'
      gethomepage.dev/group: 'A New Group'
      gethomepage.dev/icon: 'homepage.png'
      kubernetes.io/ingress.class: traefik
      # cert-manager
    className: 'traefik'
    hosts:
      - host: &host 'homepage.xlab.io'
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http

persistence:
  config:
    enabled: true
    type: configMap
    name: homepage-config
    globalMounts:
      - path: /app/config
  logs:
    enabled: true
    type: emptyDir
    globalMounts:
      - path: /app/config/logs

configMaps:
  config:
    enabled: true
    data:
      custom.js: ''
      custom.css: ''
      docker.yaml: ''
      settings.yaml: |
        background: https://images.unsplash.com/photo-1629277910650-07546caa6414?q=80&w=3027&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D
        cardBlur: md
        theme: dark
        headerStyle: boxed
        hideVersion: true
        providers:
          longhorn:
            url: https://longhorn.k3s.pro
      kubernetes.yaml: |
        mode: cluster
      widgets.yaml: |
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: 'cluster'
            nodes:
              show: true
              cpu: true
              memory: true
              showLabel: true
      services.yaml: |
        - Apps:
            - PiHole:
                icon: octoprint.png
                href: https://pihole.xlab.io/


      bookmarks.yaml: |
        - Homelab:
            - Apps Repo:
                - href: https://github.com/xalexander
                  icon: si-github

    