---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack 
  namespace: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  target:
    name: slack
    creationPolicy: Owner
    template:
      engineVersion: v2
      templateFrom:
      - target: Data
        configMap:
          name: gatus-config
          items:
            - key: config.yaml
              templateAs: Values 
    
  data:
    - secretKey: slack
      remoteRef:
        key: /gatus/slack