---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook-url 
  namespace: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  target:
    name: slack-webhook-url
    creationPolicy: Owner
  data:
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: /gatus/slack-webhook-url