---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack 
  namespace: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  target:
    name: slack
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.yaml: | 
          alerting:
            slack:
              webhook-url: "{{ .slack }}"

  data:
    - secretKey: slack
      remoteRef:
        key: /gatus/slack