---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack 
  namespace: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  target:
    name: slack
    creationPolicy: Owner
    
  data:
    - secretKey: slack
      remoteRef:
        key: /gatus/slack