---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack_webhook_url 
  namespace: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  target:
    name: slack_webhook_url
    creationPolicy: Owner
  data:
    - secretKey: slack_webhook_url
      remoteRef:
        key: /gatus/slack_webhook_url