apiVersion: v2
name: nexus
description: Rancher is open source software that combines everything an organization needs to adopt and run containers in production
version: 5.26.2
appVersion: 3.96.4
dependencies:
  - name: rancher
    repository: https://ghcr.io/stevehipwell/helm-charts/nexus3
    version: 5.26.2
