apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-conifg
  namespace: homepage
  labels:
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: homepage
    app.kubernetes.io/version: v0.9.6
    argocd.argoproj.io/instance: homepage
    helm.sh/chart: homepage-2.0.1
data:
  bookmarks.yaml: |
    - Developer:
        - Github:
            abbr: XA
            href: https://github.com/
  docker.yaml: ''
  kubernetes.yaml: |
    mode: cluster
  services.yaml: |
    - Applications:
        - Pi-Hole:
            app: pihole
            description: Pi-Hole Admin
            href: http://pihole.xlab.io
            icon: pi-hole.png
            namespace: pihole
    - My Second Group:
        - My Second Service:
            description: Homepage is the best
            href: http://localhost/
    - My Third Group: null
    - My Third Service:
        description: "Homepage is 😎"
        href: http://localhost/
  settings.yaml: ''
  widgets.yaml: |
    - resources:
        backend: kubernetes
        cpu: true
        expanded: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
    - kubernetes:
        cluster:
          cpu: true
          label: cluster
          memory: true
          show: true
          showLabel: true
        nodes:
          cpu: true
          memory: true
          show: true
          showLabel: true