apiVersion: v2
description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argocd
version: 7.8.2
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
sources:
  - https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
  - https://github.com/argoproj/argo-cd
dependencies:
  - name: argo-cd
    version: 7.8.23
    repository: https://argoproj.github.io/argo-helm
    condition: argo-cd.enabled

  - name: argocd-apps
    version: 2.0.2
    repository: https://argoproj.github.io/argo-helm
    condition: argocd-apps.enabled
