argo-cd:
  enabled: true
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: true
    resources:
      limits:
        cpu: 750m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 48Mi
  server:
    resources:
      limits:
        cpu: 250m
        memory: 128Mi
      requests:
        cpu: 25m
        memory: 48Mi
    service:
      type: LoadBalancer
      ports:
        http:
          port: 80
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: web
        # traefik.ingress.kubernetes.io/router.middlewares: traefik-default-security@kubernetescrd
        # traefik.ingress.kubernetes.io/router.tls.options: traefik-default-tls@kubernetescrd
        # traefik.ingress.kubernetes.io/router.tls: "true"
      ingressClassName: "traefik"
      hostname: &domain argocd.xlab.io
    extraArgs:
      - --insecure
  namespaceOverride: "argocd"
  # server:
  #   service:
  #     type: LoadBalancer
  #     ports:
  #       http:
  #         port: 80
argocd-apps:
  enabled: true
  applicationsets:
    core-applications:
      goTemplate: true
      generators:
        - git:
            repoURL: https://github.com/xalxnder/homelab.git
            revision: HEAD
            directories:
              - path: kubernetes-deployments/core/*
      template:
        metadata:
          name: "{{ base .path.path }}"
          labels: {}
        spec:
          project: default
          source:
            repoURL: https://github.com/xalxnder/homelab.git
            targetRevision: HEAD
            path: "{{ .path.path }}"
            helm: &appsets-helm
              valueFiles:
                - values.yaml
          destination: &appsets-destination
            server: https://kubernetes.default.svc
            namespace: "{{ .path.basename }}"
          revisionHistoryLimit: 5
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: &appsets-sync-options
              - ApplyOutOfSyncOnly=true
              - CreateNamespace=true
              - RespectIgnoreDifferences=true
              - PruneLast=true
          ignoreDifferences: []
      syncPolicy:
        preserveResourcesOnDeletion: true
        applicationsSync: sync
    observability:
      goTemplate: true
      generators:
        - git:
            repoURL: https://github.com/xalxnder/homelab.git
            revision: HEAD
            directories:
              - path: kubernetes-deployments/observability/*
      template:
        metadata:
          name: "{{ base .path.path }}"
          labels: {}
        spec:
          project: default
          source:
            repoURL: https://github.com/xalxnder/homelab.git
            targetRevision: HEAD
            path: "{{ .path.path }}"
            helm: &appsets-helm
              valueFiles:
                - values.yaml
          destination: &appsets-destination
            server: https://kubernetes.default.svc
            namespace: "{{ .path.basename }}"
          revisionHistoryLimit: 5
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: &appsets-sync-options
              - ApplyOutOfSyncOnly=true
              - CreateNamespace=true
              - RespectIgnoreDifferences=true
              - PruneLast=true
          ignoreDifferences: []
      syncPolicy:
        preserveResourcesOnDeletion: true
        applicationsSync: sync
    applications:
      goTemplate: true
      generators:
        - git:
            repoURL: https://github.com/xalxnder/homelab.git
            revision: HEAD
            directories:
              - path: kubernetes-deployments/applications/*
      template:
        metadata:
          name: "{{ base .path.path }}"
          labels: {}
        spec:
          project: default
          source:
            repoURL: https://github.com/xalxnder/homelab.git
            targetRevision: HEAD
            path: "{{ .path.path }}"
            helm: &appsets-helm
              valueFiles:
                - values.yaml
          destination: &appsets-destination
            server: https://kubernetes.default.svc
            namespace: "{{ .path.basename }}"
          revisionHistoryLimit: 5
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
            syncOptions: &appsets-sync-options
              - ApplyOutOfSyncOnly=true
              - CreateNamespace=true
              - RespectIgnoreDifferences=true
              - PruneLast=true
          ignoreDifferences: []
      syncPolicy:
        preserveResourcesOnDeletion: true
        applicationsSync: sync

