---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pihole-password
spec:
  encryptedData:
    EXTERNAL_DNS_PIHOLE_PASSWORD: AgCTPO2LQNEulhuUhkLX/kSzEkkm5gm3Nm4bzS/8krOAsB7dExeHXD4gw5KKbB76SGTSD2whVUDPAScwvTL/apKmMppgwCE40u33VDcEtcFVM1Z3FeMjiGx0ogUjfh/F0Q8Gtn0sPzWOCbzYSjTRCI4jO2IxjixKEayjYjm2pn8bFRoBJKsk8peoAO35SCT7JTYRnKl02oXjuKSQ81dg0sj4mvui2wz+Ty6D0zB6yx23EWke7CjC64oit/hjzU97CyCZka14nWEXDDOLJRqGyVD8w7cvu0Dxi770ngH/Qb6vm3FF0EQJYEFTR/CYBrGtevaxD7WXeIq214mePmITgWQoBsQvN4L+XVPMnzzGJj1yim0IBbYjDdRB1uSbhCVu6FCgsSPwWno5AGDsiUtguls1KGtNlTHu/d/LpnrlGz5p6HtyYOSxjJ7LTtHv4fKHa3u9O95r0cRrYZgI+SSaF0lFrf+SDG+86I3eD3oIXAB1VK1tJAPbMm+RcReuSwszh+eehdcTICHyToewIrdkClizMMlIl5QcEU6yIPnWhk0OTD4UwdGpMeNj9c7xen5Y83q6nsnhPgyJcQbZpQsQOhg5gW6HUcxSOf+oeWJsvwy4VNdtt1Lns9BEsTLqAIG/9VzfXJoEO0ebf203ZkvRLESN1NV9aE2UoLxiyWvHlj0s2tN9MnMzOryqLkp1IQpivTXW0RKYIC1BsAJDiIM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pihole-password
