external-dns:
  enabled: true
  fullnameOverride: external-dns
  provider: pihole
  policy: upsert-only
  registry: noop
  logLevel: debug
  image:
    tag: v0.17.0
  env:
  - name: EXTERNAL_DNS_PIHOLE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: pihole-password
        key: EXTERNAL_DNS_PIHOLE_PASSWORD
  extraArgs:
  - --pihole-server=http://192.168.1.165
  - --pihole-tls-skip-verify
  - --pihole-api-version=6
  resources:
    limits:
      cpu: 50m
      memory: 96Mi
    requests:
      cpu: 10m
      memory: 32Mi
