traefik:
  enabled: true
  fullnameOverride: traefik
  deployment:
    replicas: 1
  env:
  - name: TZ
    value: America/New_York
  additionalArguments:
  - --api.insecure
  - --ping=true
  - --serversTransport.insecureSkipVerify=true
  resources:
    requests:
      cpu: 125m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 384Mi
  logs:
    general:
      # -- Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      level: ERROR
  metrics:
    prometheus: null
  securityContext:
    capabilities:
      drop: [ ALL ]
    readOnlyRootFilesystem: true
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
  service:
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/ip-allocated-from-pool: ip-pool
      metallb.universe.tf/loadBalancerIPs: 192.168.1.78
      # external-dns.alpha.kubernetes.io/hostname: xlab.io
  ingressRoute:
    dashboard:
      enabled: true
      matchRule: (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
      services:
      - name: api@internal
        kind: TraefikService
      # -- Specify the allowed entrypoints to use for the dashboard ingress route, (e.g. traefik, web, websecure).
      # By default, it's using traefik entrypoint, which is not exposed.
      # /!\ Do not expose your dashboard without any protection over the internet /!\
      entryPoints: [ "websecure", "web" ]
      # -- Additional ingressRoute middlewares (e.g. for authentication)
      middlewares: []
      # -- TLS options (e.g. secret containing certificate)
      tls: {}

# ingressDomain: traefik.xlab.io
