traefik:
  enabled: true
  fullnameOverride: traefik
  deployment:
    replicas: 1
  env:
  - name: TZ
    value: America/New_York
  additionalArguments:
  - --api.insecure
  - --ping=true
  - --serversTransport.insecureSkipVerify=true
  resources:
    requests:
      cpu: 125m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 384Mi
  logs:
    general:
      # -- Alternative logging levels are DEBUG, PANIC, FATAL, ERROR, WARN, and INFO.
      level: DEBUG
  metrics:
    prometheus: null
  securityContext:
    capabilities:
      drop: [ ALL ]
    readOnlyRootFilesystem: true
    runAsGroup: 65532
    runAsNonRoot: true
    runAsUser: 65532
  service:
    type: LoadBalancer
    spec:
      externalTrafficPolicy: Local
    annotations:
      metallb.universe.tf/ip-allocated-from-pool: ip-pool
      metallb.universe.tf/loadBalancerIPs: 192.168.1.82
  ingressRoute:
    dashboard:
      enabled: false
