---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: pihole-pass
spec:
  encryptedData:
    password: AgBdSEQji6VsdGZBLpVNhPV/F+ATm19PCYwwuAFAitu1s7V0PytuvHVSWbbdSqKDPd+JtlfLIBlZnYsue48cKT6sAPOgu5UVvrtogQp5Gaz57PD441OC3i2MepUDUrt5t7jv0IINbJ52mpqnlxa6OLB8XDrNPxyIBvPkWHiSeFikyWCdSfPbaXFa85HdsxAbfZQiaZ6eVEMZ0cYANOvPlr8FcZHwJ3TttVrEeEGIP9V7f2VeTC8O5jyJ+ht+1kQxi/vyhlfkgeZbPTYR/xCaY/jYkb7qRwwEyHOuYRgAzOAvbJe+HYhEudPT6tNZlSM8IkEHIEHiUkH+rJzNkOcvtH3OOeEFiYGjeISpLikimKhigm4fPqAtnJ4qZz87TCrU0gfCV3FqYkZfZqogz/YyFrvGUL8xfZnu97CTDdLKrk5xvp5sonbu/c+3ReAjt/hqndW7bvERNV+3ypN4zI6j9aPsbYamyOn80TKQs7i/cd4qjfw+InxfAOkWHGoju2Ni5NYPWjSz1Xp3nhYrv2yeL2qn5ZpSXXveF4FcxNyXBaiuIB7bYcESwHqGqAiPuvNpztK6hF3ZNiV63L0MWEu1GMX+15iXKb87YHMIVGBD7E105yv9eQQcLqsf4/u4ro6aMNS/9ehJ6u7EWi7SmZJxxsQxqNlOH71XXAIlyQTNIfwIeZfA6oKjx5kAZpGRMnEcIf8OSm64JrBStA8O0Tk=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: pihole-pass
