pihole:
  enabled: true
  fullnameOverride: pihole

  serviceDns:
    mixedService: true
    type: LoadBalancer
    annotations:
      metallb.universe.tf/ip-allocated-from-pool: ip-pool
      metallb.universe.tf/loadBalancerIPs: 192.168.1.77

  serviceDhcp:
    enabled: false

  serviceWeb:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/ip-allocated-from-pool: ip-pool
      metallb.universe.tf/loadBalancerIPs: 192.168.1.76
    https:
      enabled: false

  # ingress:
  #   enabled: true
  #   annotations:
  #     cert-manager.io/cluster-issuer: lets-encrypt-production
  #     ingress.kubernetes.io/force-ssl-redirect: "true"
  #     ingress.kubernetes.io/protocol: http
  #     kubernetes.io/ingress.class: traefik
  #     kubernetes.io/tls-acme: "true"
  #     traefik.ingress.kubernetes.io/router.entrypoints: websecure
  #     traefik.ingress.kubernetes.io/router.middlewares: traefik-default-security@kubernetescrd
  #     traefik.ingress.kubernetes.io/router.tls.options: traefik-default-tls@kubernetescrd
  #     traefik.ingress.kubernetes.io/router.tls: "true"
  #   hosts:
  #   - *web-domain
  #   tls:
  #   - hosts:
  #     - *web-domain
  #     secretName: tls-secret

  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
    - 192.168.1.1

  persistentVolumeClaim:
    enabled: false
    size: 2Gi
    subPath: pihole

  resources:
    limits:
      cpu: 750m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 64Mi
  admin:
    existingSecret: "pihole-pass"
    passwordKey: "password"
