pihole:
  enabled: true
  fullnameOverride: pihole
  virtualHost: &web-domain pihole.xalab.io


  serviceDns:
    mixedService: true
    type: LoadBalancer
    annotations:
      metallb.universe.tf/ip-allocated-from-pool: ip-pool
      metallb.universe.tf/loadBalancerIPs: 192.168.1.77

  serviceDhcp:
    enabled: false

  serviceWeb:
    type: LoadBalancer
    annotations:
      metallb.universe.tf/ip-allocated-from-pool: ip-pool
      metallb.universe.tf/loadBalancerIPs: 192.168.1.76
    https:
      enabled: false

  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt-production
      kubernetes.io/ingress.class: traefik
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - *web-domain
    tls:
    - hosts:
      - *web-domain
      secretName: tls-secret

  podDnsConfig:
    enabled: true
    policy: "None"
    nameservers:
    - 192.168.1.1

  persistentVolumeClaim:
    enabled: true
    size: 2Gi
    subPath: pihole

  extraEnvVars:
    FTLCONF_dns_listeningMode: 'all'
    FTLCONF_dns_upstreams: 8.8.8.8;8.8.4.4;2001:4860:4860::8888;2001:4860:4860::884

  resources:
    limits:
      cpu: 750m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 64Mi
  admin:
    enabled: true
    existingSecret: "pihole-pass"
    passwordKey: "password"
