uptime-kuma:

  useDeploy: true

  ingress:
    enabled: true
    className: "traefik"
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt-xlab
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      traefik.ingress.kubernetes.io/router.tls: "true"
    hosts:
      - host: uptime.xalab.io
        paths:
          - path: /
            pathType: Prefix

    tls:
      - secretName: tls-secret
        hosts:
          - uptime.xalab.io

  dnsConfig:
    nameservers:
      - 192.168.1.77
    searches:
          - xalab.io
  dnsPolicy: "None"  # Override cluster DNS

  
