apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argo-cd
spec:
  project: core  # This must match the project name in values.yaml
  source:
    repoURL: https://github.com/xalxnder/homelab.git
    targetRevision: main  # Adjust if using a different branch
    path: kubernetes-deployments/core/argo-cd  # Path inside repo where Helm chart is located
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
