argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: true
  server:
    extraArgs:
      - --insecure
  namespaceOverride: "argo-cd"
  server:
    service:
      type: NodePort
      nodePort: 32080
argocd-apps:
  enabled: true
  projects:
    core:
      description: Generic project for applications
      # finalizers: &app-projects-finalizers
      #   - resources-finalizer.argocd.argoproj.io
      sourceRepos: &app-projects-source-repos
        - https://github.com/xalxnder/homelab.git
      destinations: &app-projects-destinations
        - namespace: default
          server: https://kubernetes.default.svc
        - namespace: argo-cd
          server: https://kubernetes.default.svc
      clusterResourceWhitelist: &app-projects-cluster-resource-whitelist
        - group: '*'
          kind: '*'
      namespaceResourceWhitelist: &app-projects-ns-resource-whitelist
        - group: '*'
          kind: '*'
    core:
      goTemplate: true
      generators:
        - git:
            repoURL: https://github.com/xalxnder/homelab.git
            revision: HEAD
            directories:
              - path: kubernetes-deployments/core/*
      template:
        metadata:
          name: '{{base.path.path }}'
        spec:
          project: default
          source:
            repoURL: https://github.com/xalxnder/homelab.git
            targetRevision: HEAD
            path: '{{.path.path }}'  
            helm: &appsets-helm
              valueFiles:
                - values.yaml
          destination:
            server: https://kubernetes.default.svc
            namespace: default
          syncPolicy:
            syncOptions: 
              - ApplyOutOfSyncOnly=true
              - CreateNamespace=true
              - RespectIgnoreDifferences=true
              - PruneLast=true
            automated:
              prune: false
              selfHeal: true
      syncPolicy:
        preserveResourcesOnDeletion: true
        applicationsSync: sync
