argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
  namespaceOverride: "argo-cd"
  server:
    service:
      type: NodePort
      nodePort: 32080
argocd-apps:
  enabled: true
  projects:
    applications:
      description: Generic project for applications
      finalizers: &app-projects-finalizers
        - resources-finalizer.argocd.argoproj.io
      sourceRepos: &app-projects-source-repos
        - https://github.com/xalxnder/homelab.git
      destinations: &app-projects-destinations
        - namespace: default
          server: https://kubernetes.default.svc
        - namespace: argo-cd
          server: https://kubernetes.default.svc
      clusterResourceWhitelist: &app-projects-cluster-resource-whitelist
        - group: '*'
          kind: '*'
      namespaceResourceWhitelist: &app-projects-ns-resource-whitelist
        - group: '*'
          kind: '*'
    core:
      description: Project for core services
      finalizers: *app-projects-finalizers
      sourceRepos: *app-projects-source-repos
      destinations: *app-projects-destinations
      clusterResourceWhitelist: *app-projects-cluster-resource-whitelist
      namespaceResourceWhitelist: *app-projects-ns-resource-whitelist
