argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure
  namespaceOverride: "argo-cd"
  server:
    service:
      type: NodePort
      nodePort: 32080
