---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-password
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  target:
    name: pihole-password
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /pihole/password