---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgBg6tem0maHEnN2dhOJ5KFfhnzBPftc/OP8hf6N4w9cwf+0xIC41zgUaWRySPVYeEgFYWpYbep88O10Q3TUBuVR6NoCnhtEClr+imYFMjDqhBrgsNsjz7CW9+cN2gFYoetuywplUHF9+SLiRnwee9+dqfHcaVHyYh3al8BPAvtrDWFvbWccedVQI0yjug48VC/8Gpc3R0iaDNGT/X5GbF8a50hBbQbnGjS/pW+XntMuCPyqrjlfM5pDN1x89GEygZo0Mojsns+xcDK5QHKdsiEdYpsRiU7vzUF1ZrgRJHPCHeAfBDKTe2UcAMqW9T5CnYmiIp0sMZPvZdvtg+LS7sWLXvVGHvueV5znTKIU8Jw/uQslTK4ESp7uCLNeZG6sQVCn4b64cBtmJHOm5629odWhAzc4VuFOuqDjZhqRb48U3dDx0qx096mbr/V9XjxmoEr/4OwCaJLR05EJiY9WPm6j+8bbdCu1ODfP/lNPYF0ghjBHDKqO7i8W2Kai4IALu0SsNi6XD50n7S13ZpksMxvOWXd5WmIv968fDb3rdtmLn9PUs2YmIQPEOTS2D4caiWqHqwF2vRe2rg9kw03mDFWdt9ZKKLFzAKddRSHHK7JEoHJ4nNyZFZH3+rkdk8Fvz9D3UFSJPRD12z51aMpxLACMOP+srbhEw3Rf8jJn7oqAitVw+mfqT34ly060g6l0sd9YSoFRSZodu3ai2BIHwH+mIB21bJK3KHvJ0aCL+zC8NwC4C7Dr730O
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
