---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nexus-password 
  namespace: nexus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical-secret-store
  target:
    name: nexus-password 
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: /nexus/password