postiz:
  enabled: true
  global:
    fullnameOverride: postiz
  controllers:
    postiz:
      type: deployment
      strategy: RollingUpdate
      containers:
        postiz:
          image:
            repository: ghcr.io/gitroomhq/postiz-app
            tag: v1.65.1
            pullPolicy: IfNotPresent
  service:
    postiz:
      controller: postiz
      ports:
        http:
          port: 5000

  ingress:
    postiz:
      className: "traefik"
      annotations: 
        kubernetes.io/ingress.class: traefik
        # cert-manager.io/cluster-issuer: lets-encrypt-production
        cert-manager.io/cluster-issuer: lets-encrypt-xlab
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - host: "postiz.xalab.io"
          paths:
            - path: /
              pathType: Prefix
              service:
                identifier: postiz
                port: 5000
      tls:
        - hosts:
            - postiz.xalab.io