alloy:
  enabled: true
  fullnameOverride: alloy

  daemonset:
    enabled: true

  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

  alloy:
    configMap:
      create: false
      name: alloy-config
      key: config.alloy