alloy:
  enabled: true
  fullnameOverride: alloy

  daemonset:
    enabled: true

  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
      
  podSecurityContext:
    sysctls:
      - name: fs.inotify.max_user_watches
        value: "524288"  # Recommended value

  alloy:
    configMap:
      create: true
      name: alloy-config
      key: config.alloy
      content: |
        {{ .Files.Get "config.alloy" }}
      