victoria-metrics-k8s-stack:
  enabled: true
  fullnameOverride: vm-k8s-stack
  defaultRules:
    create: false
  defaultDashboardsEnabled: true
  experimentalDashboardsEnabled: true

  grafana:
    admin:
      existingSecret: grafana-admin-credentials
      userKey: username
      passwordKey: password
    persistence:
      enabled: false
      size: 2Gi
    ingress:
      enabled: false
      annotations:
    service:
      type: NodePort
      nodePort: 32081
