victoria-metrics-k8s-stack:
  enabled: true
  fullnameOverride: vm-k8s-stack
  defaultRules:
    create: false
  defaultDashboardsEnabled: true
  experimentalDashboardsEnabled: true
  persistence:
    enabled: false
    size: 2Gi
  victoria-metrics-operator:
    enabled: true
    admissionWebhooks:
      enabled: false
 

  vmsingle:
    spec:
      storage:
        resources:
          requests:
            storage: 5Gi

  grafana:
    # admin:
    #   existingSecret: "vm-grafana-secret"
    #   userKey: admin-user
    #   passwordKey: admin-password
    persistence:
      enabled: false
      size: 2Gi
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: lets-encrypt-production
        # ingress.kubernetes.io/protocol: http
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.tls: "true"
      hosts:
        - &host grafana.xalab.io
      tls:
        - hosts:
            - *host
          secretName: tls-secret
    # service:
    #   type: LoadBalancer
