victoria-metrics-k8s-stack:
  enabled: true
  fullnameOverride: vm-k8s-stack
  defaultRules:
    create: false
  defaultDashboardsEnabled: true
  experimentalDashboardsEnabled: true
  persistence:
    enabled: false
    size: 2Gi

  vmsingle:
    spec:
      storage:
        resources:
          requests:
            storage: 5Gi

  grafana:
    # admin:
    #   userKey: username
    #   passwordKey: password
    persistence:
      enabled: false
      size: 2Gi
    ingress:
      enabled: true
      annotations:
        ingress.kubernetes.io/protocol: http
        kubernetes.io/ingress.class: traefik
        traefik.ingress.kubernetes.io/router.entrypoints: web
      hosts:
        - &domain grafana.xlab.io
    # service:
    #   type: LoadBalancer
