apiVersion: v2
name: infisical
description: A helm chart to deploy Infisical
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.5.0

dependencies:
  - name: infisical-standalone
    version: 1.5.0
    repository: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
    condition: infisical.enabled
  