infisical:
  enabled: true
  name: infisical
  fullnameOverride: "infisical"
  podAnnotations: {}
  deploymentAnnotations: {}
  replicaCount: 1
  autoDatabaseSchemaMigration: false

  image:
    repository: infisical/infisical
    tag: "v0.111.0-postgres"
    pullPolicy: IfNotPresent
  serviceAccount:
    create: true # Ensure this is defined

  affinity: {}

  kubeSecretRef: "infisical-secrets"

  service:
    annotations: {}
    type: NodePort
    nodePort: 31632

  resources:
    limits:
      memory: 210Mi
    requests:
      cpu: 200m

ingress:
  enabled: false
  hostName: ""
  ingressClassName: traefik
  nginx:
    enabled: false
  annotations: {}
  tls: []

postgresql:
  enabled: true
  name: "postgresql"
  fullnameOverride: "postgresql"
  auth:
    username: infisical
    password: root
    database: infisicalDB
  volumePermissions:
    enabled: true
  primary:
    persistence:
      enabled: true
      existingClaim: "infisical-postgres-pvc"
      mountPath: "/bitnami/postgresql"
  useExistingPostgresSecret:
    enabled: false # or false, depending on your setup

redis:
  enabled: true
  name: "redis"
  fullnameOverride: "redis"
  cluster:
    enabled: false
  usePassword: true
  auth:
    password: "mysecretpassword"
  architecture: standalone
  volumePermissions:
    enabled: true
  master:
    persistence:
      enabled: true
      existingClaim: "infisical-redis-pvc"
      path: "/redis"
