apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations:
    ingress.kubernetes.io/protocol: http
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: traefik.xlab.io
    http:
      paths:
      - backend:
          service:
            name: traefik-dashboard
            port:
              number: 8080
        path: /
        pathType: Prefix